name: Rust CI

on: [push,pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
              components: clippy,rustfmt

            - name: Check Formatting
              run: cargo fmt --all -- --check

            - name: Run Linter
              run: cargo clippy --workspace -- -D warnings

            - name: Run Tests
              run: cargo test --workspace
